<?php

/**
 * @file
 * Contains yext.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_branding_per_role module.
    case 'help.page.yext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Yext Answers is a revolutionary site search product that understands natural language and puts dynamic answers on your website to help consumers convert — right in the search results.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function yext_page_attachments(array &$page) {
  $page['#attached']['html_head'][] = [
    [
      '#attributes' => [
        'href' => 'https://assets.sitescdn.net/answers/v1.5/answers.css',
        'rel' => 'stylesheet',
        'type' => 'text/css',
      ],
      '#tag' => 'link',
    ],
    'yext_link',
  ];

  $page['#attached']['html_head'][] = [
    [
      '#attributes' => [
        'src' => 'https://assets.sitescdn.net/answers/v1.5/answers.min.js',
        'onload' => 'ANSWERS.domReady(initAnswers)',
        'defer' => TRUE,
        'async' => TRUE,
      ],
      '#tag' => 'script',
    ],
    'yext_script1',
  ];
}
